<a href="https://colab.research.google.com/github/ss-ghule/kaggle_predicting_molecular_properties/blob/master/kaggle_combined_features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
import gc
gc.collect()

552

# Not Standardized

## Train

In [2]:
!ls

connectivity_model_nn_03.h5	       structures.csv.zip
data.covs.pickle		       structures.zip
dipole_moments.csv.zip		       test.csv.zip
kaggle.json			       test_etl.csv
magnetic_shielding_tensors.csv.zip     test_feat_eng_v2_orig_my_not_std.csv
mulliken_charges.csv.zip	       test_feat_eng_v2_orig_my_std.csv
pairs_dict.pkl			       train.csv.zip
potential_energy.csv.zip	       train_etl.csv
sample_data			       train_feat_eng_v2_orig_my_not_std.csv
sample_submission.csv.zip	       train_feat_eng_v2_orig_my_std.csv
scalar_coupling_contributions.csv.zip

In [0]:
train_my=pd.read_csv('train_feat_eng_v2_orig_my_not_std.csv')
data_ext=pd.read_pickle('data.covs.pickle')

In [4]:
train_my.head()

   id     molecule_name  atom_index_0  ...  pairs_enc      bond  bond_int
0   0  dsgdb9nsd_000001             1  ...          2  0.919759         1
1   1  dsgdb9nsd_000001             1  ...         11  0.648310         1
2   2  dsgdb9nsd_000001             1  ...         11  0.648205         1
3   3  dsgdb9nsd_000001             1  ...         11  0.648170         1
4   4  dsgdb9nsd_000001             2  ...          2  0.919759         1

[5 rows x 24 columns]

In [5]:
data_ext.head()

        id     molecule_name  ...  mulliken_atom_0  mulliken_atom_1
0  5174511  dsgdb9nsd_033805  ...         0.075457        -0.088328
1  5174510  dsgdb9nsd_033805  ...         0.075457        -0.101114
2  5174509  dsgdb9nsd_033805  ...         0.075457        -0.088328
3  5174508  dsgdb9nsd_033805  ...         0.075457        -0.139609
4  5174507  dsgdb9nsd_033805  ...         0.075457        -0.221362

[5 rows x 30 columns]

In [6]:
print(train_my.shape)
print(data_ext.shape)

(4658147, 24)
(7163689, 30)

In [0]:
data_ext.drop('scalar_coupling_constant',axis=1,inplace=True)
data_ext=data_ext.fillna(0)

In [10]:
data_ext.isna().describe(include='all')

             id molecule_name  ... mulliken_atom_0 mulliken_atom_1
count   7163689       7163689  ...         7163689         7163689
unique        1             1  ...               1               1
top       False         False  ...           False           False
freq    7163689       7163689  ...         7163689         7163689

[4 rows x 29 columns]

In [11]:
train_my.columns

Index(['id', 'molecule_name', 'atom_index_0', 'atom_index_1', 'atom_0', 'x_0',
       'y_0', 'z_0', 'atom_1', 'x_1', 'y_1', 'z_1', 'mulliken_charge_0',
       'mulliken_charge_1', 'type', 'scalar_coupling_constant', 'distance',
       'type_enc', 'atom_1_enc', 'atom_0_enc', 'pairs', 'pairs_enc', 'bond',
       'bond_int'],
      dtype='object')

In [12]:
data_ext.columns

Index(['id', 'molecule_name', 'atom_index_0', 'atom_index_1', 'type', 'rc_A',
       'rc_B', 'rc_C', 'mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve',
       'U0', 'U', 'H', 'G', 'Cv', 'freqs_min', 'freqs_max', 'freqs_mean',
       'linear', 'mulliken_min', 'mulliken_max', 'mulliken_mean',
       'mulliken_atom_0', 'mulliken_atom_1'],
      dtype='object')

In [14]:
train=pd.merge(train_my,data_ext,on=['id','molecule_name','atom_index_0','atom_index_1','type'],how='left')
train.head()

   id     molecule_name  ...  mulliken_atom_0  mulliken_atom_1
0   0  dsgdb9nsd_000001  ...         0.133921        -0.535689
1   1  dsgdb9nsd_000001  ...         0.133921         0.133922
2   2  dsgdb9nsd_000001  ...         0.133921         0.133923
3   3  dsgdb9nsd_000001  ...         0.133921         0.133923
4   4  dsgdb9nsd_000001  ...         0.133922        -0.535689

[5 rows x 48 columns]

In [15]:
train.shape

(4658147, 48)

## Test

In [0]:
test_my=pd.read_csv('test_feat_eng_v2_orig_my_not_std.csv')

In [18]:
test_my.head()

        id     molecule_name  atom_index_0  ...  pairs_enc      bond  bond_int
0  4658147  dsgdb9nsd_000004             2  ...          2  0.413226         0
1  4658148  dsgdb9nsd_000004             2  ...          2  0.917924         1
2  4658149  dsgdb9nsd_000004             2  ...         11  0.173375         0
3  4658150  dsgdb9nsd_000004             3  ...          2  0.917924         1
4  4658151  dsgdb9nsd_000004             3  ...          2  0.413226         0

[5 rows x 23 columns]

In [19]:
test_my.shape

(2505542, 23)

In [22]:
test_my.columns

Index(['id', 'molecule_name', 'atom_index_0', 'atom_index_1', 'atom_0', 'x_0',
       'y_0', 'z_0', 'atom_1', 'x_1', 'y_1', 'z_1', 'mulliken_charge_0',
       'mulliken_charge_1', 'type', 'distance', 'type_enc', 'atom_1_enc',
       'atom_0_enc', 'pairs', 'pairs_enc', 'bond', 'bond_int'],
      dtype='object')

In [23]:
data_ext.columns

Index(['id', 'molecule_name', 'atom_index_0', 'atom_index_1', 'type', 'rc_A',
       'rc_B', 'rc_C', 'mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve',
       'U0', 'U', 'H', 'G', 'Cv', 'freqs_min', 'freqs_max', 'freqs_mean',
       'linear', 'mulliken_min', 'mulliken_max', 'mulliken_mean',
       'mulliken_atom_0', 'mulliken_atom_1'],
      dtype='object')

In [24]:
test=pd.merge(test_my,data_ext,on=['id','molecule_name','atom_index_0','atom_index_1','type'],how='left')
test.head()

        id     molecule_name  ...  mulliken_atom_0  mulliken_atom_1
0  4658147  dsgdb9nsd_000004  ...         0.207019        -0.207019
1  4658148  dsgdb9nsd_000004  ...         0.207019        -0.207019
2  4658149  dsgdb9nsd_000004  ...         0.207019         0.207019
3  4658150  dsgdb9nsd_000004  ...         0.207019        -0.207019
4  4658151  dsgdb9nsd_000004  ...         0.207019        -0.207019

[5 rows x 47 columns]

In [25]:
test.shape

(2505542, 47)

## Serialize not std data

In [26]:
print(train.shape)
print(test.shape)

(4658147, 48)
(2505542, 47)

In [0]:
train.to_csv('train_feat_eng_v2_orig_my_ext_not_std.csv',index=False)
test.to_csv('test_feat_eng_v2_orig_my_ext_not_std.csv',index=False)

# Standardized

## Read Data

In [0]:
!mv test_feat_eng_v2_orig_my_ext_not_std test_feat_eng_v2_orig_my_ext_not_std.csv
!mv train_feat_eng_v2_orig_my_ext_not_std train_feat_eng_v2_orig_my_ext_not_std.csv

In [4]:
!ls

connectivity_model_nn_03.h5
data.covs.pickle
dipole_moments.csv.zip
kaggle.json
magnetic_shielding_tensors.csv.zip
mulliken_charges.csv.zip
pairs_dict.pkl
potential_energy.csv.zip
sample_data
sample_submission.csv.zip
scalar_coupling_contributions.csv.zip
structures.csv.zip
structures.zip
test.csv.zip
test_etl.csv
test_feat_eng_v2_orig_my_ext_not_std.csv
test_feat_eng_v2_orig_my_not_std.csv
test_feat_eng_v2_orig_my_std.csv
train.csv.zip
train_etl.csv
train_feat_eng_v2_orig_my_ext_not_std.csv
train_feat_eng_v2_orig_my_not_std.csv
train_feat_eng_v2_orig_my_std.csv

In [5]:
train_norm=pd.read_csv('train_feat_eng_v2_orig_my_ext_not_std.csv')
train_norm.head()

   id     molecule_name  ...  mulliken_atom_0  mulliken_atom_1
0   0  dsgdb9nsd_000001  ...         0.133921        -0.535689
1   1  dsgdb9nsd_000001  ...         0.133921         0.133922
2   2  dsgdb9nsd_000001  ...         0.133921         0.133923
3   3  dsgdb9nsd_000001  ...         0.133921         0.133923
4   4  dsgdb9nsd_000001  ...         0.133922        -0.535689

[5 rows x 48 columns]

In [6]:
train_norm.shape

(4658147, 48)

## Train

In [8]:
train_norm.columns

Index(['id', 'molecule_name', 'atom_index_0', 'atom_index_1', 'atom_0', 'x_0',
       'y_0', 'z_0', 'atom_1', 'x_1', 'y_1', 'z_1', 'mulliken_charge_0',
       'mulliken_charge_1', 'type', 'scalar_coupling_constant', 'distance',
       'type_enc', 'atom_1_enc', 'atom_0_enc', 'pairs', 'pairs_enc', 'bond',
       'bond_int', 'rc_A', 'rc_B', 'rc_C', 'mu', 'alpha', 'homo', 'lumo',
       'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv', 'freqs_min',
       'freqs_max', 'freqs_mean', 'linear', 'mulliken_min', 'mulliken_max',
       'mulliken_mean', 'mulliken_atom_0', 'mulliken_atom_1'],
      dtype='object')

In [10]:
train_norm.dtypes

id                            int64
molecule_name                object
atom_index_0                  int64
atom_index_1                  int64
atom_0                       object
x_0                         float64
y_0                         float64
z_0                         float64
atom_1                       object
x_1                         float64
y_1                         float64
z_1                         float64
mulliken_charge_0           float64
mulliken_charge_1           float64
type                         object
scalar_coupling_constant    float64
distance                    float64
type_enc                      int64
atom_1_enc                    int64
atom_0_enc                    int64
pairs                        object
pairs_enc                     int64
bond                        float64
bond_int                      int64
rc_A                        float64
rc_B                        float64
rc_C                        float64
mu                          float64
alpha                       float64
homo                        float64
lumo                        float64
gap                         float64
r2                          float64
zpve                        float64
U0                          float64
U                           float64
H                           float64
G                           float64
Cv                          float64
freqs_min                   float64
freqs_max                   float64
freqs_mean                  float64
linear                      float64
mulliken_min                float64
mulliken_max                float64
mulliken_mean               float64
mulliken_atom_0             float64
mulliken_atom_1             float64
dtype: object

In [0]:
norm_cols=['x_0','y_0','z_0','x_1','y_1','z_1','mulliken_charge_0','mulliken_charge_1','distance',
           'rc_A', 'rc_B', 'rc_C', 'mu', 'alpha', 'homo', 'lumo',
           'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv', 'freqs_min',
           'freqs_max', 'freqs_mean', 'linear', 'mulliken_min', 'mulliken_max',
           'mulliken_mean', 'mulliken_atom_0', 'mulliken_atom_1']

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
std_scaler=StandardScaler()
train_norm[norm_cols]=std_scaler.fit_transform(train_norm[norm_cols])

In [14]:
train_norm.describe(include='all').T

                                count unique  ...          75%          max
id                        4.65815e+06    NaN  ...  3.49361e+06  4.65815e+06
molecule_name                 4658147  85003  ...          NaN          NaN
atom_index_0              4.65815e+06    NaN  ...           16           28
atom_index_1              4.65815e+06    NaN  ...            8           28
atom_0                        4658147      1  ...          NaN          NaN
x_0                       4.65815e+06    NaN  ...     0.637471      5.27104
y_0                       4.65815e+06    NaN  ...     0.930247      4.68229
z_0                       4.65815e+06    NaN  ...     0.631489      4.85164
atom_1                        4658147      3  ...          NaN          NaN
x_1                       4.65815e+06    NaN  ...     0.588511      5.62609
y_1                       4.65815e+06    NaN  ...     0.386976      5.12071
z_1                       4.65815e+06    NaN  ...     0.648877      5.87824
mulliken_charge_0         4.65815e+06    NaN  ...      0.14928      6.27909
mulliken_charge_1         4.65815e+06    NaN  ...     0.665464      2.82977
type                          4658147      8  ...          NaN          NaN
scalar_coupling_constant  4.65815e+06    NaN  ...      7.39065       204.88
distance                  4.65815e+06    NaN  ...     0.794823      2.12218
type_enc                  4.65815e+06    NaN  ...            5            7
atom_1_enc                4.65815e+06    NaN  ...            1            2
atom_0_enc                4.65815e+06    NaN  ...            1            1
pairs                         4658147      3  ...          NaN          NaN
pairs_enc                 4.65815e+06    NaN  ...           11           12
bond                      4.65815e+06    NaN  ...     0.539107     0.999999
bond_int                  4.65815e+06    NaN  ...            1            1
rc_A                      4.65815e+06    NaN  ... -0.000929055      824.916
rc_B                      4.65815e+06    NaN  ...     0.408421      685.876
rc_C                      4.65815e+06    NaN  ...      0.35672       589.27
mu                        4.65815e+06    NaN  ...     0.619144      14.0844
alpha                     4.65815e+06    NaN  ...     0.653239      7.21523
homo                      4.65815e+06    NaN  ...     0.515985      6.81889
lumo                      4.65815e+06    NaN  ...     0.970496      2.11108
gap                       4.65815e+06    NaN  ...     0.852853      5.18589
r2                        4.65815e+06    NaN  ...     0.428727      7.54035
zpve                      4.65815e+06    NaN  ...     0.676871      3.61655
U0                        4.65815e+06    NaN  ...     0.490469      9.78206
U                         4.65815e+06    NaN  ...     0.490456      9.78197
H                         4.65815e+06    NaN  ...     0.490456      9.78197
G                         4.65815e+06    NaN  ...     0.490498       9.7823
Cv                        4.65815e+06    NaN  ...     0.662718      3.61906
freqs_min                 4.65815e+06    NaN  ...     0.422933      31.8047
freqs_max                 4.65815e+06    NaN  ...      1.11165      1.54547
freqs_mean                4.65815e+06    NaN  ...     0.691825      31.5559
linear                    4.65815e+06    NaN  ...     0.048439     0.048439
mulliken_min              4.65815e+06    NaN  ...     0.545278      5.28513
mulliken_max              4.65815e+06    NaN  ...       0.7251      4.32794
mulliken_mean             4.65815e+06    NaN  ...     0.745181      4.25373
mulliken_atom_0           4.65815e+06    NaN  ...     0.149281      6.27985
mulliken_atom_1           4.65815e+06    NaN  ...      0.66546      2.82976

[48 rows x 11 columns]

## Test

In [15]:
test_norm=pd.read_csv('test_feat_eng_v2_orig_my_ext_not_std.csv')
test_norm.head()

        id     molecule_name  ...  mulliken_atom_0  mulliken_atom_1
0  4658147  dsgdb9nsd_000004  ...         0.207019        -0.207019
1  4658148  dsgdb9nsd_000004  ...         0.207019        -0.207019
2  4658149  dsgdb9nsd_000004  ...         0.207019         0.207019
3  4658150  dsgdb9nsd_000004  ...         0.207019        -0.207019
4  4658151  dsgdb9nsd_000004  ...         0.207019        -0.207019

[5 rows x 47 columns]

In [17]:
test_norm.shape

(2505542, 47)

In [0]:
test_norm[norm_cols]=std_scaler.transform(test_norm[norm_cols])

In [19]:
test_norm.shape

(2505542, 47)

In [20]:
test_norm.describe(include='all').T

                         count unique  ...          75%          max
id                 2.50554e+06    NaN  ...   6.5373e+06  7.16369e+06
molecule_name          2505542  45772  ...          NaN          NaN
atom_index_0       2.50554e+06    NaN  ...           16           28
atom_index_1       2.50554e+06    NaN  ...            8           28
atom_0                 2505542      1  ...          NaN          NaN
x_0                2.50554e+06    NaN  ...     0.638736      5.14306
y_0                2.50554e+06    NaN  ...     0.927555      4.90262
z_0                2.50554e+06    NaN  ...     0.634845      5.01601
atom_1                 2505542      3  ...          NaN          NaN
x_1                2.50554e+06    NaN  ...     0.588915      5.46947
y_1                2.50554e+06    NaN  ...     0.375691      5.38483
z_1                2.50554e+06    NaN  ...     0.654843      6.22421
mulliken_charge_0  2.50554e+06    NaN  ...  -7.5267e-13  -7.5267e-13
mulliken_charge_1  2.50554e+06    NaN  ...   -0.0981543     0.663743
type                   2505542      8  ...          NaN          NaN
distance           2.50554e+06    NaN  ...      0.79467      2.75857
type_enc           2.50554e+06    NaN  ...            5            7
atom_1_enc         2.50554e+06    NaN  ...            1            2
atom_0_enc         2.50554e+06    NaN  ...            1            1
pairs                  2505542      3  ...          NaN          NaN
pairs_enc          2.50554e+06    NaN  ...           11           12
bond               2.50554e+06    NaN  ...     0.541668     0.999999
bond_int           2.50554e+06    NaN  ...            1            1
rc_A               2.50554e+06    NaN  ... -0.000957481     0.206905
rc_B               2.50554e+06    NaN  ...     0.417063      53.7816
rc_C               2.50554e+06    NaN  ...     0.357786      72.1089
mu                 2.50554e+06    NaN  ...     0.606224      15.6251
alpha              2.50554e+06    NaN  ...     0.653239      8.66414
homo               2.50554e+06    NaN  ...      0.52094      5.95175
lumo               2.50554e+06    NaN  ...       0.9817      1.87355
gap                2.50554e+06    NaN  ...     0.865679      3.93963
r2                 2.50554e+06    NaN  ...     0.408867      7.23096
zpve               2.50554e+06    NaN  ...     0.678821      3.62134
U0                 2.50554e+06    NaN  ...      0.49018      8.79113
U                  2.50554e+06    NaN  ...     0.490175      8.79103
H                  2.50554e+06    NaN  ...     0.490175      8.79103
G                  2.50554e+06    NaN  ...     0.490174       8.7914
Cv                 2.50554e+06    NaN  ...      0.65598      3.59211
freqs_min          2.50554e+06    NaN  ...     0.441046      13.0283
freqs_max          2.50554e+06    NaN  ...      1.10974      1.42283
freqs_mean         2.50554e+06    NaN  ...     0.699707      5.85205
linear             2.50554e+06    NaN  ...     0.048439     0.048439
mulliken_min       2.50554e+06    NaN  ...     0.540221      4.90962
mulliken_max       2.50554e+06    NaN  ...     0.740227       3.3134
mulliken_mean      2.50554e+06    NaN  ...     0.745181      4.46637
mulliken_atom_0    2.50554e+06    NaN  ...     0.149594      5.39641
mulliken_atom_1    2.50554e+06    NaN  ...     0.665581      2.81812

[47 rows x 11 columns]

## Serialize std data

In [21]:
print(train_norm.shape)
print(test_norm.shape)

(4658147, 48)
(2505542, 47)

In [0]:
train_norm.to_csv('train_feat_eng_v2_orig_my_ext_std.csv',index=False)
test_norm.to_csv('test_feat_eng_v2_orig_my_ext_std.csv',index=False)